blas_impl:
- openblas
- mkl
- blis
blas_impl_lib:
- openblas
- mkl_rt
- blis       # [not win]
- libblis.2  # [win]
blas_default_impl:
- openblas   # [not win]
- mkl        # [win]
zip_keys:
-
  - blas_impl
  - blas_impl_lib
channel_sources:
- conda-forge/label/blasdev-main,conda-forge,defaults
- conda-forge/label/blasdev-gcc7,conda-forge/label/gcc7,defaults  # [(linux or osx)     and (environ.get('CF_COMPILER_STACK') == 'comp7')]
channel_targets:
- conda-forge blasdev-main
- conda-forge blasdev-gcc7  # [(linux or osx)     and (environ.get('CF_COMPILER_STACK') == 'comp7')]

