travis:
  secure:
    BINSTAR_TOKEN: XV2Flg5dOooLU8QWfeGS/TKLwG7V9bijNfStfSjJg0cHN6ReaJJf2ZcqiQELJ3lB+njFswreh/hpJpErDrF+KmzH7QE919kHRJbECvpb7Lj/DlqGXOhm1LiLSA5G98Q1Vz73p9C1zh3n0vZpphSQRxC562nyhViAfFpPcjzuXNsk/c3Wm+/ocLRjBkL5tEp5fCqpCVMDswYKRFfCshE8l9EHJu7jl/fsz3QlGg2LN2oM9nulbuu88riHeKgr4+3jcm5HREU56BTHx2Q2yLZ8LvBpJPt4PXrKfEl8n6QxmOGwafM5rkP22r3zYDgb0h4UEnwKpnt9o6UWzn1czzqY8UXfzZBLYw3M4JdgS0K0Cg/72phdAkwBLQK5oNouXCawVTcWrxbuR08p+Fi4Sm+p9EUmLT/zGGsK3cIMSNyRAjVyPoQ6VPFFxBtpnUMqqsDRKpnFp8V+/2OQKFL1FmwSKlTgoYu8lm/FhJNnWIsfDMqEEMhsuBOcU+V2yB6cDCCv6PQPT9lsT2cl4MjSf9MRSe0umBSNgCDfIQebksaBKe1uvgZBwvFXUgaispNNRjiiywBbxfbHtcCfKvt9VILHjqQTaMk3lftDD0h9lJ1LyEWFJlIFZ+A4os5m8PVx9vYxSaf3XJ8j095T4dlAUPTO0Sw7sD16QUoN6EIYB2R6Jmg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
