version: 2

jobs:
  build_linux_blas_implblis:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_blas_implblis"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_blas_implmkl:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_blas_implmkl"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_blas_implopenblas:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_blas_implopenblas"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_blas_implblis
      - build_linux_blas_implmkl
      - build_linux_blas_implopenblas
