jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      linux_blas_implblisblas_impl_libblisc_compilergccfortran_compilergfortran:
        CONFIG: linux_blas_implblisblas_impl_libblisc_compilergccfortran_compilergfortran
      linux_blas_implblisblas_impl_libblisc_compilertoolchain_cfortran_compilertoolchain_fort:
        CONFIG: linux_blas_implblisblas_impl_libblisc_compilertoolchain_cfortran_compilertoolchain_fort
      linux_blas_implmklblas_impl_libmkl_rtc_compilergccfortran_compilergfortran:
        CONFIG: linux_blas_implmklblas_impl_libmkl_rtc_compilergccfortran_compilergfortran
      linux_blas_implmklblas_impl_libmkl_rtc_compilertoolchain_cfortran_compilertoolchain_fort:
        CONFIG: linux_blas_implmklblas_impl_libmkl_rtc_compilertoolchain_cfortran_compilertoolchain_fort
      linux_blas_implopenblasblas_impl_libopenblasc_compilergccfortran_compilergfortran:
        CONFIG: linux_blas_implopenblasblas_impl_libopenblasc_compilergccfortran_compilergfortran
      linux_blas_implopenblasblas_impl_libopenblasc_compilertoolchain_cfortran_compilertoolchain_fort:
        CONFIG: linux_blas_implopenblasblas_impl_libopenblasc_compilertoolchain_cfortran_compilertoolchain_fort
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build